# Generated by Django 2.0.1 on 2018-01-12 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('course', models.CharField(choices=[('OAKS', 'Oaks'), ('PT', 'Panther'), ('LW', 'Lake Windcrest')], default='OAKS', max_length=4)),
                ('start_time', models.TimeField(default=datetime.time(8, 30))),
                ('gold_flight', models.BooleanField(default=True)),
                ('blue_flight', models.BooleanField(default=True)),
                ('white_flight', models.BooleanField(default=True)),
                ('num_players', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1)),
            ],
        ),
    ]
