# Generated by Django 2.0.1 on 2018-01-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_sign_up_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='major',
            field=models.BooleanField(default=False),
        ),
    ]
