# Generated by Django 2.0.1 on 2018-01-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='calcutta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pairing_party',
            field=models.BooleanField(default=False),
        ),
    ]
