# Generated by Django 2.0.1 on 2018-01-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0006_auto_20180112_1954'),
        ('tournaments', '0004_auto_20180113_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.BooleanField(default=True)),
                ('extra_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flight_color', models.IntegerField(choices=[(1, 'White'), (2, 'Blue'), (3, 'Gold'), (4, 'Black')], default=2)),
                ('flight_number', models.IntegerField(default=1)),
                ('golfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfer.Golfer')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
        ),
    ]
