# Generated by Django 2.0.1 on 2018-01-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='golfer_id',
            new_name='golfer',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
