# Generated by Django 2.0.1 on 2018-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_auto_20180115_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='place_finished',
            field=models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (99, 'DNP')], default=99, null=True),
        ),
    ]
