# Generated by Django 2.0.1 on 2018-01-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_auto_20180116_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='extra_Points',
            new_name='extra_points',
        ),
    ]
