# Generated by Django 2.0.1 on 2018-01-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0007_auto_20180115_2046'),
        ('tournaments', '0017_auto_20180116_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
    ]
