# Generated by Django 2.0.1 on 2018-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_auto_20180122_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('awayTeam', models.CharField(blank=True, max_length=50, null=True)),
                ('homeTeam', models.CharField(max_length=50)),
                ('summerBreak', models.BooleanField(default=False)),
                ('breakStart', models.DateField(blank=True, null=True)),
                ('breakEnd', models.DateField(blank=True)),
            ],
        ),
    ]
