# Generated by Django 2.0.1 on 2018-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_interclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclub',
            name='breakEnd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
