# Generated by Django 2.0.1 on 2018-01-23 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_auto_20180122_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
