# Generated by Django 2.0.1 on 2018-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0004_auto_20180112_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='board_member_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
