# Generated by Django 2.0.1 on 2018-01-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0006_auto_20180112_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'ordering': ('last_name',)},
        ),
    ]
